In [1]:
import cv2
import pandas as pd

In [2]:
#df = pd.read_csv('test_data.csv')
df = pd.read_csv('3r1-test.csv')
df.head(5)
x = df['CURRENT_FIX_X']
y = df['CURRENT_FIX_Y']
len(x)

888

In [3]:
in_slide = []

x = df['CURRENT_FIX_X']
y = df['CURRENT_FIX_Y']

top_left_x = 233
top_left_y = 74
bottom_right_x = 830 
bottom_right_y = 414
for i in range(len(x)):
    x_coord = int(x[i])
    y_coord = int(y[i])
    
    if ((top_left_x <= x_coord <= bottom_right_x) and (top_left_y <= y_coord <= bottom_right_y)):
        # Point is within the slide
        in_slide.append(1)
    else:
        in_slide.append(0)

df['in_slide'] = in_slide
df.head()

   CURRENT_FIX_X  CURRENT_FIX_Y  CURRENT_FIX_PUPIL  QUESTION  in_slide
0          496.1          363.3               2521         1         1
1          520.2          375.9               2522         1         1
2          228.0          295.1               2702         1         0
3          196.4          324.6               3117         1         0
4          193.0          330.5               3338         1         0

In [4]:
in_image = []
in_text = []
in_slide = df['in_slide']

image_top_x = 620
image_top_y = 70
image_bottom_x = 830
image_bottom_y = 420

for i in range(len(x)):
    x_coord = int(x[i])
    y_coord = int(y[i])

    if ((image_top_x <= x_coord <= image_bottom_x) and (image_top_y <= y_coord <= image_bottom_y)):
    # Point is within the slide
        in_image.append(1)
        in_text.append(0)
    else:
        if (in_slide[i] == 1):
            in_text.append(1)
            in_image.append(0)
        else:
            in_text.append(0)
            in_image.append(0)

df['in_image'] = in_image
df['in_text'] = in_text

df.head()

,CURRENT_FIX_X,CURRENT_FIX_Y,CURRENT_FIX_PUPIL,QUESTION,in_slide,in_image,in_text
0,496.1,363.3,2521,1,1,0,1
1,520.2,375.9,2522,1,1,0,1
2,228.0,295.1,2702,1,0,0,0
3,196.4,324.6,3117,1,0,0,0
4,193.0,330.5,3338,1,0,0,0

In [5]:
in_speaker = []

speaker_top_x = 84
speaker_top_y = 232
speaker_bottom_x = 668
speaker_bottom_y = 945
#
for i in range(len(x)):
    x_coord = int(x[i])
    y_coord = int(y[i])

    if ((speaker_top_x <= x_coord <= speaker_bottom_x) and (speaker_top_y <= y_coord <= speaker_bottom_y)):
    # Point is within the slide
        in_speaker.append(0)
    else:
        in_speaker.append(1)

df['in_speaker'] = in_speaker
df.head(30)

,CURRENT_FIX_X,CURRENT_FIX_Y,CURRENT_FIX_PUPIL,QUESTION,in_slide,in_image,in_text,in_speaker
0,496.1,363.3,2521,1,1,0,1,0
1,520.2,375.9,2522,1,1,0,1,0
2,228.0,295.1,2702,1,0,0,0,0
3,196.4,324.6,3117,1,0,0,0,0
4,193.0,330.5,3338,1,0,0,0,0
5,404.2,291.0,3573,1,1,0,1,0
6,370.3,319.7,3531,1,1,0,1,0
7,510.1,321.2,3337,1,1,0,1,0
8,472.6,322.4,3430,1,1,0,1,0
9,196.2,331.7,3537,1,0,0,0,0
10,198.3,326.6,3676,1,0,0,0,0
11,206.3,339.1,3820,1,0,0,0,0
12,175.2,331.2,3886,1,0,0,0,0
13,185.8,390.6,3824,1,0,0,0,0
14,201.6,514.3,4080,1,0,0,0,0
15,183.3,359.1,3981,1,0,0,0,0
16,180.5,335.6,3922,1,0,0,0,0
17,156.7,363.4,3887,1,0,0,0,0
18,170.9,533.8,3867,1,0,0,0,0
19,178.7,374.1,4113,1,0,0,0,0
20,181.7,353.4,3952,1,0,0,0,0
21,183.3,471.6,4076,1,0,0,0,0
22,188.4,367.5,3915,1,0,0,0,0
23,186.3,354.4,4141,1,0,0,0,0
24,167.2,337.2,4265,1,0,0,0,0
25,383.6,338.2,4326,1,1,0,1,0
26,753.5,453.0,4196,1,0,0,0,1
27,826.3,395.1,3628,1,1,1,0,1
28,359.5,276.1,3170,1,1,0,1,0
29,584.2,178.2,3510,1,1,0,1,1

In [7]:
df_1 = df.loc[df['QUESTION'] == 1]
df_2 = df.loc[df['QUESTION'] == 2]
df_3 = df.loc[df['QUESTION'] == 3]
df_4 = df.loc[df['QUESTION'] == 4]
df_5 = df.loc[df['QUESTION'] == 5]
df_6 = df.loc[df['QUESTION'] == 6]
df_7 = df.loc[df['QUESTION'] == 7]

In [13]:
df_1.groupby(['id', 'group', 'term']).size().unstack(fill_value=0)

AttributeError: 'Int64Index' object has no attribute 'remove_unused_levels'

In [32]:
#df = pd.read_excel('/Users/mayanksaxena/Desktop/gesture-analysis/fixation/3_l1/Output/3_l1.xls', sheet_name=None)
df = pd.read_csv('/Users/mayanksaxena/Desktop/gesture-analysis/fixation/3_l1/Output/3_l1.xls', sep = '\t')
x = df['CURRENT_FIX_X']
df.head()

,RECORDING_SESSION_LABEL,CURRENT_FIX_ADJUSTED,CURRENT_FIX_BLINK_AROUND,CURRENT_FIX_BUTTON_0_PRESS,CURRENT_FIX_BUTTON_1_PRESS,CURRENT_FIX_BUTTON_2_PRESS,CURRENT_FIX_BUTTON_3_PRESS,CURRENT_FIX_BUTTON_4_PRESS,CURRENT_FIX_BUTTON_5_PRESS,CURRENT_FIX_BUTTON_6_PRESS,...,PREVIOUS_SAC_START_Y,PREVIOUS_SAC_START_Y_RESOLUTION,TRIAL_FIXATION_TOTAL,TRIAL_INDEX,TRIAL_LABEL,TRIAL_START_TIME,VIDEO_FRAME_INDEX_END,VIDEO_FRAME_INDEX_START,VIDEO_NAME_END,VIDEO_NAME_START
0,l1,False,AFTER,.,.,.,.,.,.,.,...,.,.,776,1,Trial: 1,88282,7,.,bicycle_fullX.xvd,.
1,l1,False,BOTH,.,.,.,.,.,.,.,...,382.00,35.20,776,1,Trial: 1,88282,24,18,bicycle_fullX.xvd,bicycle_fullX.xvd
2,l1,False,BEFORE,.,.,.,.,.,.,.,...,234.50,35.80,776,1,Trial: 1,88282,36,35,bicycle_fullX.xvd,bicycle_fullX.xvd
3,l1,False,NONE,.,.,.,.,.,.,.,...,555.20,35.50,776,1,Trial: 1,88282,49,36,bicycle_fullX.xvd,bicycle_fullX.xvd
4,l1,False,NONE,.,.,.,.,.,.,.,...,430.30,35.30,776,1,Trial: 1,88282,56,50,bicycle_fullX.xvd,bicycle_fullX.xvd

In [33]:
x

0       561.4
1       191.2
2       617.6
3       630.5
4       594.5
5       417.5
6       425.3
7       352.3
8       315.6
9       332.3
10      384.7
11      437.5
12      837.0
13      824.2
14      780.4
15      179.3
16      153.7
17      192.9
18      359.8
19      348.9
20      410.8
21      485.5
22      638.0
23      834.8
24      874.0
25      372.7
26      194.5
27      200.3
28      194.6
29      176.9
        ...
746     210.6
747     216.1
748     201.1
749     467.9
750     414.8
751     418.9
752     194.9
753     175.2
754     203.1
755     233.6
756     220.2
757     182.6
758     847.1
759     880.3
760    1036.8
761     953.7
762     863.9
763     178.6
764     170.2
765     210.3
766     222.7
767     186.1
768     162.9
769     209.4
770     202.1
771     202.3
772     197.6
773     173.9
774     178.8
775     179.0
Name: CURRENT_FIX_X, Length: 776, dtype: float64